import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components";
import SessionProvider from "@/utils/SessionProvider";
import Providers from "@/Providers";
import { getServerSession } from "next-auth";
import 'svgmap/dist/svgMap.min.css';




const josefin = Josefin_Sans({ 
  subsets: ['latin'], 
  weight: ['400', '700'] // specify the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();
  return (
    <html lang="en" data-theme="light">
      <body className={josefin.className}>
      <SessionProvider session={session}>
        <Header />
        <Providers>
        {children}
        </Providers>
        {/*<Footer />*/}
      </SessionProvider>
        </body>
    </html>
  );
}
